name: Collect Games Poll Reactions

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect_votes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load poll ID
        run: echo "MESSAGE_ID=$(cat .poll_id)" >> "$GITHUB_ENV"

      - name: Fetch poll message
        run: |
          echo "Fetching poll message ID: $MESSAGE_ID"
          RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X GET "https://discord.com/api/v10/channels/${{ secrets.DISCORD_CHANNEL_ID }}/messages/${MESSAGE_ID}" \
            -H "Authorization: Bot ${{ secrets.DISCORD_BOT_TOKEN }}")

          HTTP_STATUS=$(echo "$RESPONSE" | grep HTTP_STATUS | cut -d: -f2)
          JSON_CONTENT=$(echo "$RESPONSE" | sed '/HTTP_STATUS/d')

          if [ "$HTTP_STATUS" != "200" ]; then
            echo "⚠️ Poll message not found or deleted (status $HTTP_STATUS). Skipping."
            exit 0
          fi

          echo "$JSON_CONTENT" > .poll_message.json

      - name: Generate results
        run: |
          mkdir -p results/games
          EMOJIS=(🇦 🇧 🇨 🇩 🇪 🇫 🇬 🇭 🇮 🇯 🇰 🇱 🇲 🇳 🇴 🇵 🇶 🇷 🇸 🇹 🇺 🇻 🇼 🇽 🇾 🇿)

          jq -r '.reactions[]? | "\(.emoji.name) \(.count)"' .poll_message.json > .reaction_counts.txt || true

          NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          TODAY=$(date -u +'%Y-%m-%d')
          GAMES=$(cat .used_game_slugs.txt)

          echo "{" > results/games_results.json
          echo "  \"votes\": [" >> results/games_results.json

          i=0
          while read -r SLUG; do
            GAME_JSON="games/${SLUG}.json"
            TITLE=$(jq -r '.title' "$GAME_JSON")
            URL=$(jq -r '.url' "$GAME_JSON")
            EMOJI="${EMOJIS[i]}"
            RAW=$(grep "$EMOJI" .reaction_counts.txt | awk '{print $2}')
            VOTES=${RAW:-0}
            if [ "$VOTES" -gt 0 ]; then VOTES=$((VOTES - 1)); fi
            if [ $i -gt 0 ]; then echo "," >> results/games_results.json; fi
            echo "    {\"slug\": \"$SLUG\", \"title\": \"$TITLE\", \"url\": \"$URL\", \"votes\": $VOTES}" >> results/games_results.json
            i=$((i + 1))
          done <<< "$GAMES"

          echo "  ]," >> results/games_results.json
          echo "  \"generatedAt\": \"${NOW}\"" >> results/games_results.json
          echo "}" >> results/games_results.json

          cp results/games_results.json "results/games/${TODAY}.json"

      - name: Commit results
        run: |
          git config --global user.name "poll-bot"
          git config --global user.email "bot@example.com"
          git add results/games_results.json results/games/*.json
          git commit -m "Update game poll results and archive" || echo "No changes to commit."
          git push || echo "Nothing to push."
