name: Collect Owner Poll Reactions

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect_owners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load poll ID
        run: echo "OWNER_POLL_ID=$(cat .owner_poll_id)" >> $GITHUB_ENV

      - name: Fetch ✅ reactions and determine present owners
        run: |
          mkdir -p .tmp

          ENCODED=$(printf "✅" | jq -sRr @uri)
          RESPONSE=$(curl -s "https://discord.com/api/v10/channels/${{ secrets.DISCORD_OWNERS_CHANNEL_ID }}/messages/${OWNER_POLL_ID}/reactions/${ENCODED}?limit=100" \
            -H "Authorization: Bot ${{ secrets.DISCORD_BOT_TOKEN }}")

          echo "$RESPONSE" > .tmp/reacted_yes.json
          jq -r '.[].username' .tmp/reacted_yes.json | sort -u > .tmp/reacted_usernames.txt

          touch .present_owners
          while read -r OWNER; do
            DISCORD_USER=$(jq -r --arg owner "$OWNER" '.[$owner] // empty' .owners_map.json)
            if grep -iqFx "$DISCORD_USER" .tmp/reacted_usernames.txt; then
              echo "$OWNER" >> .present_owners
              echo "✔️ $OWNER is present (matched with $DISCORD_USER)"
            fi
          done < <(jq -r 'keys[]' .owners_map.json)

          sort -u .present_owners -o .present_owners

      - name: Commit present owners
        run: |
          git config --global user.name "poll-bot"
          git config --global user.email "bot@example.com"
          if [ -s .present_owners ]; then
            git add .present_owners
            git commit -m "Update present owners from owner poll"
            git push
          else
            echo "⚠️ No owners marked present. Skipping commit."
          fi

          git commit -m "Update present owners from owner poll"
          git push
