name: Generate games/index.json

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate index.json
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const dir = 'games';
          const out = path.join(dir, 'index.json');
          const files = fs.readdirSync(dir).filter(f => f.endsWith('.json') && f !== 'index.json');
          const list = files.map(f => {
            const filePath = path.join(dir, f);
            const json = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
            if (json.comingSoon) return null;
            return { slug: f.replace('.json', ''), owner: json.owner || null };
          }).filter(Boolean);
          fs.writeFileSync(out, JSON.stringify(list, null, 2));
          "

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add games/index.json
          git commit -m "Update games index.json" || echo "No changes"
          git push
